// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	buyer "github.com/cpereira42/mercado-fresco-pron4/internal/buyer"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: card_number_ID, first_name, last_name
func (_m *Repository) Create(card_number_ID string, first_name string, last_name string) (buyer.Buyer, error) {
	ret := _m.Called(card_number_ID, first_name, last_name)

	var r0 buyer.Buyer
	if rf, ok := ret.Get(0).(func(string, string, string) buyer.Buyer); ok {
		r0 = rf(card_number_ID, first_name, last_name)
	} else {
		r0 = ret.Get(0).(buyer.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(card_number_ID, first_name, last_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]buyer.Buyer, error) {
	ret := _m.Called()

	var r0 []buyer.Buyer
	if rf, ok := ret.Get(0).(func() []buyer.Buyer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]buyer.Buyer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetId provides a mock function with given fields: id
func (_m *Repository) GetId(id int) (buyer.Buyer, error) {
	ret := _m.Called(id)

	var r0 buyer.Buyer
	if rf, ok := ret.Get(0).(func(int) buyer.Buyer); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(buyer.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, card_number_ID, first_name, last_name
func (_m *Repository) Update(id int, card_number_ID string, first_name string, last_name string) (buyer.Buyer, error) {
	ret := _m.Called(id, card_number_ID, first_name, last_name)

	var r0 buyer.Buyer
	if rf, ok := ret.Get(0).(func(int, string, string, string) buyer.Buyer); ok {
		r0 = rf(id, card_number_ID, first_name, last_name)
	} else {
		r0 = ret.Get(0).(buyer.Buyer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, string, string) error); ok {
		r1 = rf(id, card_number_ID, first_name, last_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
