-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 20:59:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mercadofresco2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercadofresco2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercadofresco2` DEFAULT CHARACTER SET utf8mb3 ;
USE `mercadofresco2` ;

-- -----------------------------------------------------
-- Table `mercadofresco2`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`buyer` (
  `id` INT(11) NOT NULL,
  `card_number_id` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `card_number_id_UNIQUE` (`card_number_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`countries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`provinces` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `province_name` VARCHAR(255) NOT NULL,
  `id_contry_fk` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provinces_contries1_idx` (`id_contry_fk` ASC) VISIBLE,
  CONSTRAINT `fk_provinces_contries1`
    FOREIGN KEY (`id_contry_fk`)
    REFERENCES `mercadofresco2`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`localities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `locality_name` VARCHAR(255) NOT NULL,
  `province_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localities_provinces1_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_localities_provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `mercadofresco2`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`carries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`carries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `locality_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carries_localities1_idx` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `fk_carries_localities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `mercadofresco2`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`warehouse` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `warehouse_code` VARCHAR(255) NOT NULL,
  `locality_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `warehouse_code_UNIQUE` (`warehouse_code` ASC) VISIBLE,
  INDEX `fk_warehouse_localities1_idx` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_localities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `mercadofresco2`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`employee` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `card_number_id` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `warehouse_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `card_number_id_UNIQUE` (`card_number_id` ASC) VISIBLE,
  INDEX `fk_employee_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mercadofresco2`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`products_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`products_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`seller` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(255) NOT NULL,
  `locality_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC) VISIBLE,
  INDEX `fk_seller_localities1_idx` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `fk_seller_localities1`
    FOREIGN KEY (`locality_id`)
    REFERENCES `mercadofresco2`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `expiration_rate` DECIMAL(19,2) NOT NULL,
  `freezing_rate` DECIMAL(19,2) NOT NULL,
  `height` DECIMAL(19,2) NOT NULL,
  `length` DECIMAL(19,2) NOT NULL,
  `net_weight` DECIMAL(19,2) NOT NULL,
  `product_code` VARCHAR(255) NOT NULL,
  `recommended_freezing_temperature` DECIMAL(19,2) NOT NULL,
  `width` DECIMAL(19,2) NOT NULL,
  `product_type_id` INT(11) NOT NULL,
  `seller_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_code_UNIQUE` (`product_code` ASC) VISIBLE,
  INDEX `fk_product_seller1_idx` (`seller_id` ASC) VISIBLE,
  INDEX `fk_product_products_types1_idx` (`product_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_products_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `mercadofresco2`.`products_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mercadofresco2`.`seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`sections` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `section_number` VARCHAR(255) NOT NULL,
  `current_capacity` INT(11) NOT NULL,
  `current_temperature` DECIMAL(19,2) NOT NULL,
  `maximum_capacity` INT(11) NOT NULL,
  `minimum_capacity` INT(11) NOT NULL,
  `minimum_temperature` DECIMAL(19,2) NOT NULL,
  `product_type_id` INT(11) NOT NULL,
  `warehouse_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_products_types1_idx` (`product_type_id` ASC) VISIBLE,
  INDEX `fk_section_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  UNIQUE INDEX `section_number_UNIQUE` (`section_number` ASC) VISIBLE,
  CONSTRAINT `fk_section_products_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `mercadofresco2`.`products_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_section_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mercadofresco2`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`products_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`products_batches` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `batch_number` VARCHAR(255) NOT NULL,
  `current_quantity` INT(11) NOT NULL,
  `current_temperature` DECIMAL(19,2) NOT NULL,
  `due_date` DATETIME NOT NULL,
  `initial_quantity` INT(11) NOT NULL,
  `manufacturing_date` DATETIME NOT NULL,
  `manufacturing_hour` DATETIME NOT NULL,
  `minimum_temperature` DECIMAL(19,2) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `section_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_batches_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_products_batches_section1_idx` (`section_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_batches_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mercadofresco2`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_batches_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `mercadofresco2`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`inbound_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`inbound_orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `order_number` VARCHAR(255) NOT NULL,
  `employe_id` INT(10) UNSIGNED NOT NULL,
  `product_batch_id` INT(11) NOT NULL,
  `warehouse_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inbound_details_products_batches1_idx` (`product_batch_id` ASC) VISIBLE,
  INDEX `fk_inbound_details_employee1_idx` (`employe_id` ASC) VISIBLE,
  INDEX `fk_inbound_details_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_inbound_details_employee1`
    FOREIGN KEY (`employe_id`)
    REFERENCES `mercadofresco2`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbound_details_products_batches1`
    FOREIGN KEY (`product_batch_id`)
    REFERENCES `mercadofresco2`.`products_batches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbound_details_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mercadofresco2`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`product_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`product_records` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `last_update_date` DATETIME NOT NULL,
  `purchase_price` DECIMAL(19,2) NOT NULL,
  `sale_price` DECIMAL(19,2) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_records_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_records_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mercadofresco2`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`order_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`purchase_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`purchase_orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(255) NOT NULL,
  `order_date` DATETIME NOT NULL,
  `tracking_code` VARCHAR(255) NOT NULL,
  `buyer_id` INT(11) NOT NULL,
  `carrier_id` INT(11) NOT NULL,
  `order_status_id` INT(11) NOT NULL,
  `warehouse_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_orders_carries1_idx` (`carrier_id` ASC) VISIBLE,
  INDEX `fk_purchase_orders_warehouse1_idx` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_purchase_orders_buyer1_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `fk_purchase_orders_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_orders_buyer1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `mercadofresco2`.`buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_carries1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `mercadofresco2`.`carries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `mercadofresco2`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_orders_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `mercadofresco2`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`order_details` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `clean_liness_status` VARCHAR(255) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `temperature` DECIMAL(19,2) NOT NULL,
  `product_record_id` INT(11) NOT NULL,
  `purchase_order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_details_product_records1_idx` (`product_record_id` ASC) VISIBLE,
  INDEX `fk_order_details_purchase_orders1_idx` (`purchase_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_product_records1`
    FOREIGN KEY (`product_record_id`)
    REFERENCES `mercadofresco2`.`product_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_details_purchase_orders1`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `mercadofresco2`.`purchase_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `rol_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mercadofresco2`.`user_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadofresco2`.`user_rol` (
  `user_id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  INDEX `fk_user_rol_rol1_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_user_rol_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `mercadofresco2`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rol_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mercadofresco2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
