// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	section "github.com/cpereira42/mercado-fresco-pron4/internal/section"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateSection provides a mock function with given fields: _a0
func (_m *Repository) CreateSection(_a0 section.Section) (section.Section, error) {
	ret := _m.Called(_a0)

	var r0 section.Section
	if rf, ok := ret.Get(0).(func(section.Section) section.Section); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(section.Section)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(section.Section) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSection provides a mock function with given fields: id
func (_m *Repository) DeleteSection(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListarSectionAll provides a mock function with given fields:
func (_m *Repository) ListarSectionAll() ([]section.Section, error) {
	ret := _m.Called()

	var r0 []section.Section
	if rf, ok := ret.Get(0).(func() []section.Section); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]section.Section)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListarSectionOne provides a mock function with given fields: id
func (_m *Repository) ListarSectionOne(id int64) (section.Section, error) {
	ret := _m.Called(id)

	var r0 section.Section
	if rf, ok := ret.Get(0).(func(int64) section.Section); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(section.Section)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSection provides a mock function with given fields: _a0
func (_m *Repository) UpdateSection(_a0 section.Section) (section.Section, error) {
	ret := _m.Called(_a0)

	var r0 section.Section
	if rf, ok := ret.Get(0).(func(section.Section) section.Section); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(section.Section)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(section.Section) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
